module.exports = {
  setting: {
    ghoulEnabled: true,
    vol: 30,
    blockLiveStream: false,
    delayRange: [200, 800],
    autoClose: false,
    autoDrive: false,
    minimalism: false,
    autoOpenBox: true,
    blockEnterEffect: false,
    autoAnswerEnabled: false,
    autoRefreshFreq: '0',
    blockEnterBarrage: false,
    rocketOnly: false,
    netTimeSync: true,
    showTips: true,
    ghoulMode: 'normal',
    gfksax: 12,
    autoSendBarrageEnabled: true,
  },
  stat: {
    box: 0,
    zan: 0,
    wen: 0,
    song: 0,
    silver: 0,
    day: null,
  },
};
