module.exports = {
  setting: {
    ghoulEnabled: true,
    vol: 60,
    blockLiveStream: false,
    delayRange: [1000, 2000],
    autoClose: false,
    minimalism: false,
    autoOpenBox: true,
    blockEnterEffect: false,
    autoAnswerEnabled: false,
    autoRefreshFreq: '0',
    blockEnterBarrage: false,
    rocketOnly: false,
    netTimeSync: true,
    ghoulMode: 'normal',
    autoSendBarrageEnabled: true,
    notificationShow: true,
    blockRoomAd: false,
    nobleBarrageExp: 'off',
    boxFilter: 'all',
    gfksax: 6,
    pcNotificationEnabled: true,
  },
  stat: {
    box: 0,
    zan: 0,
    wen: 0,
    song: 0,
    silver: 0,
    day: null,
  },
};
